version: '3.8'

services:
  l8tetools:
    image: l8tenever/l8tetools:latest
    container_name: l8tetools
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=change-me-in-production
    restart: unless-stopped
    volumes:
      - l8te_data:/app/instance

volumes:
  l8te_data:
